service: what-the-chuck
frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  graphql:
    handler: src/app.handler
    events:
      - http:
          path: graphql
          method: any
          cors: true
