version: 2.1

commands:
  restore_backend_cache_cmd:
    steps:
      - restore_cache:
          keys:
            - backend-cache
  save_backend_cache_cmd:
    steps:
      - save_cache:
          paths: [node_modules]
          key: backend-cache

jobs:
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_backend_cache_cmd
      - run:
          name: Build back-end
          command: |
            npm install
            npm run build
      - save_backend_cache_cmd

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_backend_cache_cmd
      - run:
          name: Test back-end
          command: |
            npm run test

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_backend_cache_cmd
      - run:
          name: Audit back-end
          command: |
            npm audit --audit-level=critical

workflows:
  my_workflow:
    jobs:
      - build-backend
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
