version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: say hello world
          command: |
            echo "hello world!"

workflows:
  my_workflow:
    jobs:
      - hello-world